[phases.setup]
nixPkgs = [
  "python312",
  "postgresql_16.dev",
  "gcc",
  "coreutils",
  "findutils",
  "glibc"
]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "playwright install --with-deps chromium"
]

[phases.build]
cmds = [
  ". /opt/venv/bin/activate",
  "echo 'Build completed successfully'"
]

[start]
cmd = "python run_scraper.py"
