[phases.setup]
nixPkgs = [
  "python312",
  "postgresql_16.dev",
  "gcc",
  "coreutils",
  "findutils",
  "glibc",
  "glib",
  "gobject-introspection",
  "nss",
  "dbus",
  "atk",
  "at-spi2-atk",
  "expat",
  "at-spi2-core",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "mesa",
  "xorg.libxcb",
  "libxkbcommon",
  "systemd",
  "alsa-lib",
  "fontconfig",
  "freetype",
  "pango",
  "cairo",
  "gtk3"
]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "playwright install chromium"
]

[phases.build]
cmds = [
  ". /opt/venv/bin/activate",
  "echo 'Build completed successfully'"
]

[start]
cmd = "python run_scraper.py"
