[phases.setup]
nixPkgs = [
  "python311",
  "postgresql_16.dev",
  "gcc",
  "chromium",
  "chromedriver",
  "coreutils",
  "findutils",
  "glibc",
  "nss",
  "fontconfig",
  "freetype",
  "mesa",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXrandr",
  "xorg.libXi",
  "xorg.libXcursor",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "gtk3",
  "pango",
  "cairo",
  "alsa-lib",
  "cups",
  "dbus"
]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  ". /opt/venv/bin/activate",
  "echo 'Build completed successfully'"
]

[start]
cmd = "python run_scraper.py"
