[phases.setup]
nixPkgs = [
  "python311",
  "postgresql_16.dev",
  "gcc",
  "chromium",
  "chromedriver",
  "coreutils",  # Provides ls, echo, test, and other basic commands
  "findutils"   # Provides find command
]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  ". /opt/venv/bin/activate",
  "echo 'Build completed successfully'"
]

[start]
cmd = "python run_scraper.py"
